sudo: required
language: node_js
env:
  - CXX="g++-4.8"

node_js:
  - '4.1'
  - '4.0'
  - "iojs"
  - "iojs-v2"
  - "iojs-v1"
  - '0.12'
  - '0.10'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
